/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Zhe

import Zhe.lib.*
import kotlin.test.Test
import kotlin.test.assertNotNull
// import org.awaitility.kotlin.*

class AppTest {

    @Test fun containsShouldCallTriggerWhenAStringCotainsAnother() {
        
    }
}
