/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Zhe
import Zhe.lib.*

val openTags: Parser = regex("<a>")
val closeTags: Parser = regex("</a>")

fun main() {
    val runner = Runner()

    runner.addEvent(regex("YOU <a> alguma outra") contains "<a> alguma",
        { values ->
            println(values)
        }
    )

    runner.addEvent(integer,
        { values ->
            println(values)
        }
    )

    runner.addEvent(regex("Hey "),
        { values ->
            println(values)
        }
    )

    runner.addEvent(regex("YOU <a>") + " alguma outra",
        { values ->
            println(values)
        }
    )

    runner.addEvent(regex("Hey") and regex(" alguma outra"),
        { values ->
            println(values)
        }
    )

    runner.addEvent(openTags / "outra" and regex("alguma") / closeTags,
        { values ->
            println(values)
        }
    )

    runner.invoke("Hey 12 YOU <a> alguma outra </a> coisa")
}
