/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Zhe
import Zhe.lib.*

val openTags: Parser = regex("<") + string + ">"
val closeTags: Parser = regex("</") + string + ">"

fun main(args: Array<String>) {
    val runner = Runner()

    runner.addEvent(
        SequencingEvent(arrayOf(regex("Hey") / "alguma", closeTags / openTags),
        { values ->
            println(values)
        }
    ))

    runner.invoke("Hey YOU <a> alguma outra coisa </a>")
}
